[[constraint]]
  name = "github.com/Azure/azure-sdk-for-go"
  version = "12.0.0-beta"

[[constraint]]
  name = "github.com/Azure/azure-storage-blob-go"
  version = "0.1.1"

[[constraint]]
  branch = "master"
  name = "github.com/denisenkom/go-mssqldb"

[[constraint]]
  branch = "master"
  name = "github.com/marstr/randname"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "1.1.0"

[[constraint]]
  name = "github.com/subosito/gotenv"
  version = "1.1.0"
