[[constraint]]
  name = "github.com/Azure/azure-sdk-for-go"
  version = "15.0.1"

[[constraint]]
  name = "github.com/Azure/azure-storage-blob-go"
  version = "0.1.1"

[[constraint]]
  name = "github.com/Azure/go-autorest"
  version = "10.6.0"

[[constraint]]
  branch = "master"
  name = "github.com/denisenkom/go-mssqldb"

[[constraint]]
  name = "github.com/globalsign/mgo"
  version = "r2018.04.03"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "1.2.0"

[[constraint]]
  name = "github.com/subosito/gotenv"
  version = "1.1.0"

[prune]
  go-tests = true
  unused-packages = true
