[[constraint]]
  name = "github.com/Azure/azure-sdk-for-go"
  version = "14.0.0"

[[constraint]]
  name = "github.com/Azure/azure-storage-blob-go"
  branch = "master"

[[constraint]]
  name = "github.com/Azure/go-autorest"
  version = "10.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/denisenkom/go-mssqldb"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "1.2.0"

[[constraint]]
  name = "github.com/subosito/gotenv"
  version = "1.1.0"

[prune]
  go-tests = true
  unused-packages = true
